services:
  portainer-backup:
    container_name: portainer-backup
    image: antlac1/portainer-backup:latest
    hostname: portainer-backup
    restart: unless-stopped
    command: schedule
    environment:
      TZ: America/New_York
      PORTAINER_BACKUP_URL: "http://${SERVER}:9000"
      PORTAINER_BACKUP_TOKEN: "${PORTAINER_ACCESS_TOKEN}"
      PORTAINER_BACKUP_PASSWORD: "${BU_PASSWORD}"
      PORTAINER_BACKUP_OVERWRITE: 1
      PORTAINER_BACKUP_SCHEDULE: "0 47 * * * *"
      PORTAINER_BACKUP_STACKS: 1
      PORTAINER_BACKUP_DRYRUN: 0
      PORTAINER_BACKUP_CONCISE: 1
      PORTAINER_BACKUP_DIRECTORY: "/backup"
      PORTAINER_BACKUP_FILENAME: "portainer-backup-{{DATETIME}}.tar.gz"
    volumes:
      - /root/portainer-backups:/backup