services:
    docker-android:
        command: 'Galaxy S10" -e WEB_VNC=true --device /dev/kvm --name android-container budtmo/docker-android:emulator_11.0'
        image: budtmo/docker-android:emulator_11.0
        devices:
            - /dev/kvm
        environment:
            - EMULATOR_DEVICE="Galaxy S10"
            - WEB_VNC=true
        volumes:
            - android-data:/home/androidusr
        ports:
            - '6080:6080'

volumes:
  android-data:
    driver: local